### ISSUE TITLE
Build voacb with test/val sets?

### ISSUE THREAD

**Issue by daqingliu** [lichengunc/MAttNet#7]
Thanks for your great codes.
I found that while building vocab in "prepro.py", it seems didn't filter those sents from **test/val sets** out, which may cause information leakage?
And what's **forbidden words**? Where do those words come from?
Did I misunderstand or ignore something? Looking forward your reply~

**Comment by lichengunc** [comment]
Yeah, I realized the problem when I was preparing the script for this model. Just want to keep the consistency with my previous RE work (it's been several years) as I don't feel it would change something, so kept the setting. :-) It's absolutely correct by making a ``train'' vocab only. 
Forbidden words are manually prepared (empirically) due to imperfect performance of refer-parser.
